default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: career_compiler
  host: localhost
  username: yuma
  password:

test:
  <<: *default
  database: career_compiler_test
  host: localhost
  username: yuma
  password:

production:
  <<: *default
  database: career_compiler_db
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

queue:
  <<: *default
  database: career_compiler_queue_db
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

cable:
  <<: *default
  database: career_compiler_db
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

cache:
  <<: *default
  database: career_compiler_cache_db
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>