default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: career_compiler_development

test:
  <<: *default
  database: career_compiler_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
